# Generated by Django 5.2.15 on 2026-06-21 14:36

import django.core.validators
import django.db.models.deletion
import players.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', players.fields.LevelField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('7.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='matches.match')),
                ('sponsored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions_sponsored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companions_companion',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['match'], name='companions_match_idx'), models.Index(fields=['sponsored_by'], name='companions_sponsor_idx')],
            },
        ),
    ]
