# Generated by Django 5.2.15 on 2026-06-21 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('match_created', 'Match created'), ('match_joined', 'Player joined'), ('match_left', 'Player left'), ('match_cancelled', 'Match cancelled')], max_length=32)),
                ('channel', models.CharField(choices=[('push', 'Expo Push'), ('email', 'Resend email')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (opt-out)')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notificationlog',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='notif_user_created_idx'), models.Index(fields=['status'], name='notif_status_idx'), models.Index(fields=['event_type'], name='notif_event_idx')],
            },
        ),
    ]
