# Generated by Django 5.2.15 on 2026-06-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Admins can disable a slot without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_slots', to='clubs.court')),
            ],
            options={
                'db_table': 'match_slots_matchslot',
                'ordering': ('start_time',),
                'indexes': [models.Index(fields=['start_time'], name='match_slots_start_idx'), models.Index(fields=['court', 'is_active'], name='match_slots_court_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('court', 'start_time'), name='match_slots_court_start_uniq'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='match_slots_end_after_start')],
            },
        ),
    ]
