# Generated by Django 5.2.15 on 2026-06-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companions', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_authored', to='companions.companion')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_authored', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matches.match')),
            ],
            options={
                'db_table': 'chat_chatmessage',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['match', 'id'], name='chat_msg_match_id_idx'), models.Index(fields=['created_at'], name='chat_msg_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('author_companion__isnull', True), ('author_user__isnull', False)), models.Q(('author_companion__isnull', False), ('author_user__isnull', True)), _connector='OR'), name='chat_chatmessage_author_xor')],
            },
        ),
    ]
