# Generated by Django 5.2.15 on 2026-06-21 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(help_text='Required physical address — used for uniqueness checks.', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clubs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clubs_club',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='clubs.club')),
            ],
            options={
                'db_table': 'clubs_court',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Slot duration in minutes; must be >= 15.', validators=[django.core.validators.MinValueValidator(15)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clubs.court')),
            ],
            options={
                'db_table': 'clubs_schedule',
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['name'], name='clubs_club_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='clubs_club_name_address_uniq'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('address', ''), _negated=True), name='clubs_club_address_required'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['club', 'is_active'], name='clubs_court_club_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='clubs_court_club_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['court', 'weekday'], name='clubs_schedule_court_wd_idx'),
        ),
    ]
