# Generated by Django 5.2.15 on 2026-06-21 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(help_text='Users who can manage this club (CRUD courts/schedules, slots).', related_name='administered_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_by',
            field=models.ForeignKey(help_text='Original creator; kept for audit. Use ``admins`` for access control.', on_delete=django.db.models.deletion.PROTECT, related_name='clubs_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
