# Generated by Django 5.2.15 on 2026-06-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_admins_alter_club_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
    ]
