# Generated by Django 5.2.15 on 2026-06-21 14:33

import django.core.validators
import django.db.models.deletion
import players.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_min', players.fields.LevelField(decimal_places=2, default=Decimal('2.75'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('7.00'))])),
                ('level_max', players.fields.LevelField(decimal_places=2, default=Decimal('4.25'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('7.00'))])),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_match',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_matchplayer',
                'ordering': ('joined_at',),
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['host'], name='matches_match_host_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_cancelled'], name='matches_match_cancelled_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('level_max__gt', models.F('level_min'))), name='matches_match_level_range_invariant'),
        ),
        migrations.AddIndex(
            model_name='matchplayer',
            index=models.Index(fields=['user'], name='matches_matchplayer_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchplayer',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='matches_matchplayer_match_user_uniq'),
        ),
    ]
