# Generated by Django 5.2.15 on 2026-06-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clubs.club'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['club'], name='players_user_club_idx'),
        ),
    ]
